#!/bin/bash

echo -e "<style>span{color:orange;}</style><span>Thank you for installing AlwaysRemindMe 😊</span>"
echo -e "<style>span{color:orange;}</style><span>Please send me some Feedback ✌️</span>"
